using CustomPatches;
using HarmonyLib;
using MCM.Abstractions.Base.Global;
using SandBox.GauntletUI.AutoGenerated;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.ComponentInterfaces;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade;

namespace CustomPatches
{
	public class CustomPatches : MBSubModuleBase
	{
		public static MCMSettings Settings { get; private set; }

		private bool isInitialized = false;

		protected override void OnBeforeInitialModuleScreenSetAsRoot()
		{
			base.OnBeforeInitialModuleScreenSetAsRoot();
			if (isInitialized)
				return;

			Settings = GlobalSettings<MCMSettings>.Instance;
			if (Settings == null)
				throw new Exception("Settings is null");

			isInitialized = true;
		}

		protected override void OnSubModuleLoad()
		{
			base.OnSubModuleLoad();

			try
			{
				new Harmony("sy.custompatches").PatchAll(Assembly.GetExecutingAssembly());
			}
			catch (Exception exc)
			{
				FileLog.Log($"{exc.GetType()} {exc.Message}\n{exc.StackTrace}");
			}
		}
	}
}
